### ISSUE TITLE
Fails to build with `syn 2.0.39`

### ISSUE THREAD

**Issue by omerfirmak** [udoprog/genco#50]
```
error[E0603]: trait `CustomToken` is private
  --> /home/omer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/genco-macros-0.17.7/src/token.rs:11:18
   |
11 | impl syn::token::CustomToken for Eof {
   |                  ^^^^^^^^^^^ private trait
   |
note: the trait `CustomToken` is defined here
  --> /home/omer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/syn-2.0.39/src/token.rs:92:16
   |
92 | pub(crate) use self::private::CustomToken;
   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
help: consider importing this trait instead
   |
11 | impl syn::__private::CustomToken for Eof {
   |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~

For more information about this error, try `rustc --explain E0603`.
```

**Comment by udoprog** [comment]
Thanks for bringing this to my attention. Since CustomToken is not public API this is not supposed to have been used. So I'll remove it ASAP.

**Comment by udoprog** [comment]
This should be fixed in genco `0.17.8`.
